name: Build Custom Image
on:
  workflow_dispatch:
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1
        with:
          recipe: recipe.yml
          push: false
