name: Build Custom Image
on:
  pull_request:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.11
        with:
          recipe: ${{ matrix.recipe }}
          push: false
          maximize_build_space: true
