name: Build ISO
on:
  workflow_dispatch:
jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build ISO
        uses: blue-build/github-action@v1
        with:
          recipe: recipe.yml
          build_iso: true
          push: false
          upload_results: true
